//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportActivate.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContantResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContantResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SupportActivate.Common.ContantResource", typeof(ContantResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----KEY NOT DEFINED----.
        /// </summary>
        internal static string allKeyNOTDEFINED {
            get {
                return ResourceManager.GetString("allKeyNOTDEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----All Key OEM----.
        /// </summary>
        internal static string allKeyOEM {
            get {
                return ResourceManager.GetString("allKeyOEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----All Key Retail----.
        /// </summary>
        internal static string allKeyRetail {
            get {
                return ResourceManager.GetString("allKeyRetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----All Key Volume:MAK----.
        /// </summary>
        internal static string allKeyVolume {
            get {
                return ResourceManager.GetString("allKeyVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked IID..
        /// </summary>
        internal static string Blocked_IID {
            get {
                return ResourceManager.GetString("Blocked_IID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceeded IID..
        /// </summary>
        internal static string Exceeded_IID {
            get {
                return ResourceManager.GetString("Exceeded_IID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 (Blocked).
        /// </summary>
        internal static string KeyBlock {
            get {
                return ResourceManager.GetString("KeyBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xC004C003.
        /// </summary>
        internal static string KeyRetai4C003 {
            get {
                return ResourceManager.GetString("KeyRetai4C003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xC004C008.
        /// </summary>
        internal static string KeyRetai4C008 {
            get {
                return ResourceManager.GetString("KeyRetai4C008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xC004C060.
        /// </summary>
        internal static string KeyRetai4C060 {
            get {
                return ResourceManager.GetString("KeyRetai4C060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key block.
        /// </summary>
        internal static string KeyRetaiBlock {
            get {
                return ResourceManager.GetString("KeyRetaiBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to call M$ Support..
        /// </summary>
        internal static string Need_to_call {
            get {
                return ResourceManager.GetString("Need_to_call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not legimate key. Maybe blocked..
        /// </summary>
        internal static string Not_legimate_key {
            get {
                return ResourceManager.GetString("Not_legimate_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KEY NOT DEFINED.
        /// </summary>
        internal static string NOTDEFINED {
            get {
                return ResourceManager.GetString("NOTDEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEM.
        /// </summary>
        internal static string OEM {
            get {
                return ResourceManager.GetString("OEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail.
        /// </summary>
        internal static string Retail {
            get {
                return ResourceManager.GetString("Retail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server too busy..
        /// </summary>
        internal static string serverBusy {
            get {
                return ResourceManager.GetString("serverBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported PKeyConfig file or Invalid Key.
        /// </summary>
        internal static string Unsupported_PKeyConfig_InvalidKey {
            get {
                return ResourceManager.GetString("Unsupported_PKeyConfig_InvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume:MAK.
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong IID..
        /// </summary>
        internal static string Wrong_IID {
            get {
                return ResourceManager.GetString("Wrong_IID", resourceCulture);
            }
        }
    }
}
