//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportActivate.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessagesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SupportActivate.Common.MessagesResource", typeof(MessagesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add note error..
        /// </summary>
        internal static string AddNoteError {
            get {
                return ResourceManager.GetString("AddNoteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The advanced check will lose 1 activation for online key or key volume..
        /// </summary>
        internal static string AdvancedCheckPidkey {
            get {
                return ResourceManager.GetString("AdvancedCheckPidkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Disabled Service.
        /// </summary>
        internal static string CannotDisabledService {
            get {
                return ResourceManager.GetString("CannotDisabledService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Enabled Service.
        /// </summary>
        internal static string CannotEnabledService {
            get {
                return ResourceManager.GetString("CannotEnabledService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to convert the product key to a key block?.
        /// </summary>
        internal static string ChangeKeyToKeyBlocked {
            get {
                return ResourceManager.GetString("ChangeKeyToKeyBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Confirmation ID is in the wrong format. Or there is no Confirmation ID..
        /// </summary>
        internal static string CIDWrong {
            get {
                return ResourceManager.GetString("CIDWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to delete all key..
        /// </summary>
        internal static string DeleteAllKey {
            get {
                return ResourceManager.GetString("DeleteAllKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the product key?.
        /// </summary>
        internal static string DeleteKey {
            get {
                return ResourceManager.GetString("DeleteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to delete 1 of 2 data sources..
        /// </summary>
        internal static string DeleteSourceKey1Or2 {
            get {
                return ResourceManager.GetString("DeleteSourceKey1Or2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the key.
        /// </summary>
        internal static string EnterPidkey {
            get {
                return ResourceManager.GetString("EnterPidkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory overflow.
        /// </summary>
        internal static string MemoryOverflow {
            get {
                return ResourceManager.GetString("MemoryOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to turn on multithreading. Windows 7 and Office 2010 keys do not support multithreading.
        /// </summary>
        internal static string MultythreadNoSupportWin7Off10 {
            get {
                return ResourceManager.GetString("MultythreadNoSupportWin7Off10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no Confirmation ID..
        /// </summary>
        internal static string NoCID {
            get {
                return ResourceManager.GetString("NoCID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the command..
        /// </summary>
        internal static string NoSelectCommand {
            get {
                return ResourceManager.GetString("NoSelectCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not sorted.
        /// </summary>
        internal static string NotSoft {
            get {
                return ResourceManager.GetString("NotSoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please perform the operation again..
        /// </summary>
        internal static string OperationAgain {
            get {
                return ResourceManager.GetString("OperationAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please update to a newer version of Support Activate! Do you want to Update?.
        /// </summary>
        internal static string PleaseUpdateNewerVersion {
            get {
                return ResourceManager.GetString("PleaseUpdateNewerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recheck information key error..
        /// </summary>
        internal static string RecheckInforError {
            get {
                return ResourceManager.GetString("RecheckInforError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recheck information key success..
        /// </summary>
        internal static string RecheckInforSuccess {
            get {
                return ResourceManager.GetString("RecheckInforSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to recover the product key?.
        /// </summary>
        internal static string RecoverKey {
            get {
                return ResourceManager.GetString("RecoverKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery Product Key Block error.
        /// </summary>
        internal static string RecoverKeyError {
            get {
                return ResourceManager.GetString("RecoverKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery Product Key Block success.
        /// </summary>
        internal static string RecoverKeySuccess {
            get {
                return ResourceManager.GetString("RecoverKeySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will reopen as an administrator.
        /// </summary>
        internal static string ReopenWithAdmin {
            get {
                return ResourceManager.GetString("ReopenWithAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save complete.
        /// </summary>
        internal static string SaveComplete {
            get {
                return ResourceManager.GetString("SaveComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Error.You need to recover the configuration file..
        /// </summary>
        internal static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Success.
        /// </summary>
        internal static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process will stop after the current key is checked..
        /// </summary>
        internal static string StopPidKey {
            get {
                return ResourceManager.GetString("StopPidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token getcid cannot be empty..
        /// </summary>
        internal static string TokenApiCannotEmpty {
            get {
                return ResourceManager.GetString("TokenApiCannotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to update Token getcid?.
        /// </summary>
        internal static string UpdateTokenGetcid {
            get {
                return ResourceManager.GetString("UpdateTokenGetcid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
    }
}
